name: pharmed_core
description: Domain models, entities, enums and repository interfaces
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.9.0

  pharmed_data:
    path: ../pharmed_data
  pharmed_ui:
    path: ../pharmed_ui
  pharmed_utils:
    path: ../pharmed_utils
  
dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.7.0


resolution: workspace
